"""Tests for per-reply provenance records (auditable history).

Covers:
  * build_record: fields, secret redaction, base_url reduced to host,
    numbered sources, deterministic zh/en description.
  * Integrity: record_sha256 recomputes; any edit fails verification.
  * Storage round-trip, list_records ordering, Markdown report content.
  * Reproducibility bundle: zip contents and manifest hashes.
  * End-to-end (subprocess, isolated state dirs): start_chat with web search
    stores a verified provenance record whose sources match the search and
    whose system-prompt hash covers the injected search context.
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


SEARCH = {
    "ok": True,
    "query": "CRISPR off-target",
    "engines": ["pubmed", "openalex"],
    "quality": {"relevance": 0.6, "source_count": 2, "authoritative_count": 1, "verified": True},
    "warnings": [],
    "sources": [
        {"title": "Off-target effects", "url": "https://pubmed.ncbi.nlm.nih.gov/123/", "snippet": "x" * 900, "source": "pubmed"},
        {"title": "Guide design", "url": "https://openalex.org/W1", "snippet": "y", "source": "openalex"},
    ],
    "context_markdown": "## Deep information search results\n- [Off-target effects](https://pubmed.ncbi.nlm.nih.gov/123/)",
}


def _route(**extra):
    from ali import provenance

    ri = {
        "provider": "deepseek",
        "model": "deepseek-chat",
        "base_url": "https://api.deepseek.com/v1?api_key=abc",
        "api_key": "sk-THISSHOULDNEVERAPPEAR0000",
        "tier": "C2",
        "route_key": "office",
        "thinking_depth": "medium",
        "max_tokens": 4096,
        "chat_engine": "direct",
        "skills": ["literature-review"],
        "skills_source": "auto",
        "grounding": {"workspace": "/data/lab", "entry_count": 42, "excerpts": 2},
        "execution_mode": "workflow",
        "_workflow_id": "research_review",
        "_search": provenance.compact_search(SEARCH),
    }
    ri.update(extra)
    return ri


def _record(**extra):
    from ali import provenance

    return provenance.build_record(
        session_id="s1",
        message_id="m1",
        stream_id="st1",
        user_message="Summarise CRISPR off-target literature",
        preamble="system prompt with key sk-ABCDEFGHIJKLMNOPQRSTUV inside",
        final_text="Answer [1]",
        route_info=_route(),
        tools=[{"name": "web_search", "preview": "query=crispr"}],
        grounding_check={"ok": True, "soft": True},
        elapsed_ms=12300,
        started_at=1_700_000_000.0,
        **extra,
    )


def test_build_record_fields_and_redaction():
    from ali import provenance

    rec = _record()
    assert rec["schema"] == provenance.SCHEMA
    assert rec["model"]["provider"] == "deepseek"
    assert rec["model"]["base_url_host"] == "api.deepseek.com"
    assert rec["model"]["max_tokens"] == 4096
    assert rec["request"]["workflow_id"] == "research_review"
    assert rec["request"]["sha256"] == hashlib.sha256("Summarise CRISPR off-target literature".encode()).hexdigest()
    blob = json.dumps(rec)
    assert "THISSHOULDNEVERAPPEAR" not in blob
    assert "ABCDEFGHIJKLMNOPQRSTUV" not in blob
    sp = rec["context"]["system_prompt"]
    assert sp["masked_secrets"] == 1
    # hash covers what was actually sent, not the masked copy
    assert sp["sha256"] == provenance.sha256_text("system prompt with key sk-ABCDEFGHIJKLMNOPQRSTUV inside")
    assert rec["environment"]["app_version"]
    assert rec["timing"]["elapsed_ms"] == 12300


def test_sources_numbered_in_prompt_order_and_snippets_truncated():
    rec = _record()
    srcs = rec["search"]["sources"]
    assert [s["n"] for s in srcs] == [1, 2]
    assert srcs[0]["domain"] == "pubmed.ncbi.nlm.nih.gov"
    assert srcs[0]["engine"] == "pubmed"
    assert len(srcs[0]["snippet"]) <= 280


def test_description_is_deterministic_plain_language():
    rec = _record()
    zh, en = rec["description"]["zh"], rec["description"]["en"]
    assert "deepseek/deepseek-chat" in zh and "C2·office" in zh and "12.3s" in zh
    assert "检索 2 条来源" in zh and "调用工具 1 次" in zh and "literature-review" in zh
    assert en.startswith("Generated by deepseek/deepseek-chat")
    assert _record()["description"] == rec["description"]


def test_integrity_hash_detects_tampering():
    from ali import provenance

    rec = _record()
    assert provenance.verify_record(rec)
    rec["model"]["model"] = "gpt-4o"
    assert not provenance.verify_record(rec)
    assert not provenance.verify_record({"schema": provenance.SCHEMA})


def test_save_load_list_and_summary():
    from ali import provenance

    with tempfile.TemporaryDirectory() as tmp, mock.patch.object(provenance, "PROV_DIR", Path(tmp)):
        rec = _record()
        path = provenance.save_record(rec)
        assert path.is_file() and path.parent.name == "s1"
        loaded = provenance.load_record("s1", "m1")
        assert loaded == json.loads(json.dumps(rec))
        assert provenance.verify_record(loaded)
        assert provenance.load_record("s1", "../../etc") is None
        assert [r["message_id"] for r in provenance.list_records("s1")] == ["m1"]
        summ = provenance.summary(loaded)
        assert summ["sources"] == 2 and summ["tools"] == 1
        assert summ["record_sha256"] == loaded["integrity"]["record_sha256"]


def test_markdown_report_lists_sources_tools_and_hashes():
    from ali import provenance

    rec = _record()
    md = provenance.render_markdown(rec)
    assert "Provenance report" in md
    assert "[Off-target effects](https://pubmed.ncbi.nlm.nih.gov/123/)" in md
    assert "`web_search`" in md
    assert rec["integrity"]["record_sha256"] in md
    assert "✓ verified" in md


def test_reproducibility_bundle_manifest_matches_files():
    from ali import provenance
    from ali import sessions as store

    with tempfile.TemporaryDirectory() as tmp:
        tmp_p = Path(tmp)
        (tmp_p / "sessions").mkdir()
        with mock.patch.object(provenance, "PROV_DIR", tmp_p / "prov"), \
                mock.patch.object(store, "SESSIONS_DIR", tmp_p / "sessions"), \
                mock.patch.object(store, "ensure_state_dirs", lambda: None):
            session = store.create_session(title="Bundle test")
            rec = provenance.build_record(
                session_id=session.id,
                message_id="m1",
                user_message="q",
                final_text="a",
                route_info=_route(),
            )
            provenance.save_record(rec)
            data, name = provenance.export_session_bundle(rec["session_id"])
    assert name.endswith(".zip")
    zf = zipfile.ZipFile(io.BytesIO(data))
    names = set(zf.namelist())
    assert {"session.json", "REPORT.md", "MANIFEST.json", "provenance/m1.json"} <= names
    manifest = json.loads(zf.read("MANIFEST.json"))
    for fname, digest in manifest["files"].items():
        assert hashlib.sha256(zf.read(fname)).hexdigest() == digest
    assert manifest["records"][0]["verified"] is True
    assert "sk-THISSHOULDNEVERAPPEAR" not in zf.read("provenance/m1.json").decode()


E2E_SCRIPT = r"""
import json, sys, time
sys.path.insert(0, sys.argv[1])
from ali import sessions as store, streaming, provenance, websearch

SEARCH = json.loads(sys.argv[2])
websearch.search_structured = lambda *a, **k: SEARCH
s = store.create_session(title="e2e")
sid = s.id
res = streaming.start_chat(sid, "请检索 CRISPR 脱靶效应的最新文献并总结", web_search=True)
deadline = time.time() + 60
while time.time() < deadline:
    msgs = store.get_session(sid).messages
    if any(m.get("role") == "assistant" for m in msgs):
        break
    time.sleep(0.2)
msg = [m for m in store.get_session(sid).messages if m.get("role") == "assistant"][-1]
rec = provenance.load_record(sid, msg["id"])
print(json.dumps({
    "summary": msg.get("provenance"),
    "verified": provenance.verify_record(rec) if rec else False,
    "sources": [s["url"] for s in ((rec or {}).get("search") or {}).get("sources") or []],
    "stream_id": res["stream_id"],
    "record_stream": (rec or {}).get("stream_id"),
    "prompt_has_search": SEARCH["context_markdown"] in (((rec or {}).get("context") or {}).get("system_prompt") or {}).get("text", ""),
}))
"""


def test_start_chat_records_verified_provenance_end_to_end():
    with tempfile.TemporaryDirectory() as tmp:
        env = dict(os.environ)
        env.update(
            {
                "HERMES_ALI_STATE_DIR": str(Path(tmp) / "state"),
                "AGENT_CLI_HOME": str(Path(tmp) / "agent-cli"),
                "HERMES_HOME": str(Path(tmp) / "hermes"),
                "HOME": tmp,
                "HERMES_ALI_AGENT_DIR": str(Path(tmp) / "no-agent"),
            }
        )
        proc = subprocess.run(
            [sys.executable, "-c", E2E_SCRIPT, str(ROOT), json.dumps(SEARCH)],
            env=env,
            capture_output=True,
            text=True,
            timeout=120,
        )
    assert proc.returncode == 0, proc.stderr[-2000:]
    out = json.loads(proc.stdout.strip().splitlines()[-1])
    assert out["summary"] and out["summary"]["schema"] == "agent-hub.provenance/1"
    assert out["verified"] is True
    assert out["sources"] == [s["url"] for s in SEARCH["sources"]]
    assert out["record_stream"] == out["stream_id"]
    assert out["prompt_has_search"] is True
